services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - db_data:/data
    restart: unless-stopped
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    # command: /bin/bash    # Run bash but keep container alive

volumes:
  db_data: 
